### ISSUE TITLE
ffmpeg error

### ISSUE THREAD

**Issue by silenteyes705** [thecoder75/liveme-tools#124]
[log file removed for security purposes]

**Comment by thecoder75** [comment]
Uploading the log file for ffmpeg exposed your username on your computer plus provided other personal information that should not be here so I removed it to protect you.

For best support, please provide what version of the LiveMe Tools you're using.  Also note that recent versions employing the chunk download option has been documented as causing corrupt segments and shortened videos to be processed due to triggering of anti-leech security on the Live.me servers.
