### ISSUE TITLE
Converting to NW.js

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#48]
The conversion would solve some more major pressing issues we're experiencing right now plus simplify the development as we wouldn't have to constantly use IPC bridges between different windows and could actually help streamline the code for better performance and maintenance.

This is just me thinking about it and opening a discussion on this matter as we're hitting some barriers right now in the current development we're working with.

**Comment by thecoder75** [comment]
This is something that I keep thinking about and revisiting the topic myself for thoughts.  

This site kind of gives some info on each and actually leans more towards why NWjs would be better than Electron for the LiveMe Tools.

http://freecontent.manning.com/how-does-node-js-work-with-nw-js-and-electron/

**Comment by thecoder75** [comment]
Another good informative site:

https://www.smashingmagazine.com/2017/03/beyond-browser-web-desktop-apps/

**Comment by thecoder75** [comment]
There are some other things too for thought about doing this conversion:

- Adapt the use of Web Storage for Settings and other data storage (like Favorites, History and Queue)
- Reduction of the amount of code required to do most commands and functions (remove need of IPC and use Singularity of modules and/or direct function calls.)

The more I review how we would write things in NWjs vs Electron, the more I see less code writing and lean more towards NWjs.

**Comment by polydragon** [comment]
I don't think switching to NWjs would solve the IPC 'issue.' It still has it's own IPC bridge for communicating between processes.

- We could already do this if we wanted, but as it's a desktop app it makes more sense to save the data to a file. The user then can back it up, share it, restore an old version, whatever. Though it doesn't really matter for the few amount of settings we have.
- We would already get this if we did things 'properly' the first time, having the modules in the main process.

I'm confused about this - you didn't want to move over to Angular because of the work required to get it done, yet you're thinking about moving to NW.js which would take an equal amount of work... to get XP support? At least with Angular I can add a check to see if we're running in Electron and if we're not we can disable all Node features - meaning it would run on XP and any phone those other small amounts of people are asking for.

It's your project, obviously, so you can take it in any direction that you want.

**Comment by thecoder75** [comment]
I just started this as a discussion of whether the project would really benefit from switching to NWjs or staying with Electron and what would the pros/cons be.  NWjs runs everything in a single process vs Electron's isolated renderers/processes was the original review that started me thinking about all this.  The need to run under Windows XP or on mobile is not something I'm worried about at all as I had a request from a few on that, not enough to warrant working on and wasn't a thought during all this research.

The main question that came to mind though was would this project been better off being started on NWjs back in the beginning or did I make the right choice with Electron.  We're facing issues now that we both never thought about or realized before and now have to rewrite large portions of the code.

**Comment by polydragon** [comment]
I joined this project with a minimal knowledge of Electron, and for me it was a good learning experience. So questionable decisions like putting the Downloads module in the main window instead of the main process wasn't the greatest idea. So there are two options we really have here:

- Rewrite a lot of the code and switch to NW.js. Including a new build process, and all of the bugtesting that comes with it.
- Rewrite the modules to work in the main thread, then either:
  1.  Use IPC to communicate with it.
  2.  OR use `myModule = require('electron').remote.require('./my/module')` to get the module instance directly (need more research).

To me, it seems unnecessary to rewrite most of the backbone of the app to switch to a different system rather than just replacing the modules with the way we should have done it in the first place.

**Comment by thecoder75** [comment]
I'm curious too about module instance and will look into it as well.  

Will skip moving/converting to NWjs, and yes its been a learning curve for me as well.

Closing this ticket.
