### ISSUE TITLE
New 6.0.0 Branch Development

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#60]
- [x] Switch to using the LiveMe API module
- [x] Switch to using native window controls and menus from custom ones
- [x] Cleanup of some of the code
- [x] Cleanup of the page layouts
- [x] Cleanup of the page styling (Also convert to a more simpler more common structure)
- [x] Add LiveMeOMG browser/viewer
- [x] Fix/improve import function, move to its own renderer and code module to fix minor issues.
- [X] Create custom controls for video player
- [x] Add custom handlers for messages to video player like jump to time index, etc...

**Comment by thecoder75** [comment]
I was actually thinking of adding an option to overlay the chat in the bottom of the video window like Periscope style or something.

**Comment by polydragon** [comment]
I had originally thought of that, but I came up with this. 

The pros would be that it looks nicer and it takes less space.

The cons would be that you can only see what is said at the current time, and you can't skip forward or backwards without adding some tricky scrollbar, but then that gets in the way of the video and can make it confusing for some people.

The main issue is that you can't look at other messages at other points of time in the video without making it overly complex - which is why I added the feature in the first place, so that you can skip parts of the broadcast you don't really want to watch. I doubt our users are sitting there through every broadcast they might want to watch, from start to finish. They want to see if the broadcast contains something they like, then they might do so after.

**Comment by thecoder75** [comment]
Update has been completed.  We will look into updating/changing the message history in another minor update.
