### ISSUE TITLE
maintain a history for users

### ISSUE THREAD

**Issue by ushall** [thecoder75/liveme-tools#87]
[feature request] : maintain a history of users for which informations were at least once displayed, similar to the downloaded files history which are displayed on a green background.

Thanks for the fans / followings search filter, very useful, however could be even better if implemented as a filter-as-you type list.

**Comment by thecoder75** [comment]
This is something that has been thought about, the only problem I see is that after awhile, some of the accounts marked as previously seen may have new replays available which might get missed.

One option was to have it timeout the entries after a day or two to reset them to unseen so you know to visit them again in the future or something.

I want to discuss this more as there's too many small factors involved that need to be discussed and planned before this type of feature is implemented.

**Comment by ushall** [comment]
you're right : we may want to revisit already seen users, while for others we are pretty sure we won't one seen them a fraction of seconds ;)
Another way of addressing that duality would be a Tinder-like system : accept / reject ;)

**Comment by thegeezer9999** [comment]
What about something like the green highlighting for when you have downloaded a video except in this case, maybe a flag for "viewed" might help ? This way, there would at least be a way of keeping track of everything you have VIEWED, which would then by logical deduction give you a way of viewing videos you had NOT viewed. So maybe the next enhancement could be a NOT VIEWED since last visit of all your favourites ? I realize this is probably a big undertaking, but a staged implementation might make this easier ? I realize also this would mean returning an array of videos per user each time the application is re-opened or refreshed, and logically this would return these in a list sorted by USER and then VIDEOID. Clicking on USER would take you to their "home" page, clicking on a video link would provide the options to view/download etc. (again this could be a third enhancement, initially just opening the user "home" page and allowing the user the usual options to download the non-flagged VIDEO(s). Just a thought.

**Comment by thecoder75** [comment]
Currently this feature is now available in the 7.0.0 release series with a hard-coded 1 day timeout on entries.  I will be adding support to custom set the timeout in Settings.

**Comment by monstergarden** [comment]
Hm maybe the information when last visited should be displayed instead of removing the highlight

**Comment by thecoder75** [comment]
Since the Fans and Followings windows are getting more packed and cluttered, the last visited date could only be added to the regular profile view on the left side of the main window.

Doing so would really serve no purpose as people would get used to skipping visited profiles thus defeating the whole purpose of show the last visited date.

It has been discussed previously and is being checked into about adding additional buttons allowing setting different durations to keep a profile marked longer than the defaults.  (1 Week, 1 Month, Forever, etc...)

**Comment by thecoder75** [comment]
I've added the Settings option and tested and completed its integration in the 7.0.1 release.
