### ISSUE TITLE
remember position of windows on the screen

### ISSUE THREAD

**Issue by ushall** [thecoder75/liveme-tools#88]
For now all windows open at the very same place on the screen : centered. this is not very practical and require to manually reorganize windows. a suggestion would be to remember a x,y position for each kind of windows : main, fans, followings, download queue.. and use it for the next windows to be opened.

**Comment by thecoder75** [comment]
Good point, not something that was previously discussed or touched upon.  I do agree as I find myself moving windows around when doing test builds all the time.

**Comment by ushall** [comment]
Yeah, the best would be to have a unique window desktop application with one or two panels for the lists, but this may be more time consuming and also requires some design thinking.

**Comment by thecoder75** [comment]
I've added support in the 6.2.0 branch for remembering positions of the main, player, queue and favorites windows only.  The Fans and Following windows are dynamically generated and since its possible to have multiples of those open it could cause problems adding the support for them.

Maybe in a future release I'll add support for remembering those windows as well.
